
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Banner from '@/Components/Banner'
import Image from 'next/image'
import Card from '@/Components/Card'
import  coffeeStoresData from "../data/coffestores.json"
import { fetchCoffeeStores } from '../lib/coffe-stores'

export async function getStaticProps(context:any) {
  console.log("hi getStaticProps");
  const coffeeStores = await fetchCoffeeStores();

  return {
    props: {
      
      coffeeStores,
    }, // will be passed to the page component as props
  };
}
export default function Home(props:any) {
  console.log("props", props);
  const handleOnBannerBtnClick = () => {
    console.log("hi banner button");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Hub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image src="/hero-image.png" width={700} height={200} alt='img' />
        </div>
        {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map((coffeeStore:any) => {
                return (
                  <Card
                    key={coffeeStore.fsq_id}
                    name={coffeeStore.name}
                    imgUrl={
                      coffeeStore.imgUrl ||
                      "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"
                    }
                   
                    href={`/coffestore/${coffeeStore.fsq_id}`}
                    className={styles.card}
                  />
                );
              })}
            </div>
          </>
        )}
      </main>
    </div>
  );
}

